// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto
#ifndef GRPC_hello_2eproto__INCLUDED
#define GRPC_hello_2eproto__INCLUDED

#include "hello.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace helloworld {

class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "helloworld.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::helloworld::GetEchoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::GetEchoResponse>> AsyncGetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::GetEchoResponse>>(AsyncGetEchoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::GetEchoResponse>> PrepareAsyncGetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::GetEchoResponse>>(PrepareAsyncGetEchoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest* request, ::helloworld::GetEchoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest* request, ::helloworld::GetEchoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::GetEchoResponse>* AsyncGetEchoRaw(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::GetEchoResponse>* PrepareAsyncGetEchoRaw(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::helloworld::GetEchoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::GetEchoResponse>> AsyncGetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::GetEchoResponse>>(AsyncGetEchoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::GetEchoResponse>> PrepareAsyncGetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::GetEchoResponse>>(PrepareAsyncGetEchoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest* request, ::helloworld::GetEchoResponse* response, std::function<void(::grpc::Status)>) override;
      void GetEcho(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest* request, ::helloworld::GetEchoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::helloworld::GetEchoResponse>* AsyncGetEchoRaw(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::helloworld::GetEchoResponse>* PrepareAsyncGetEchoRaw(::grpc::ClientContext* context, const ::helloworld::GetEchoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetEcho_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetEcho(::grpc::ServerContext* context, const ::helloworld::GetEchoRequest* request, ::helloworld::GetEchoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetEcho : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetEcho() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetEcho() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEcho(::grpc::ServerContext* /*context*/, const ::helloworld::GetEchoRequest* /*request*/, ::helloworld::GetEchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEcho(::grpc::ServerContext* context, ::helloworld::GetEchoRequest* request, ::grpc::ServerAsyncResponseWriter< ::helloworld::GetEchoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetEcho<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetEcho : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetEcho() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::helloworld::GetEchoRequest, ::helloworld::GetEchoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::helloworld::GetEchoRequest* request, ::helloworld::GetEchoResponse* response) { return this->GetEcho(context, request, response); }));}
    void SetMessageAllocatorFor_GetEcho(
        ::grpc::MessageAllocator< ::helloworld::GetEchoRequest, ::helloworld::GetEchoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::helloworld::GetEchoRequest, ::helloworld::GetEchoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetEcho() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEcho(::grpc::ServerContext* /*context*/, const ::helloworld::GetEchoRequest* /*request*/, ::helloworld::GetEchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetEcho(
      ::grpc::CallbackServerContext* /*context*/, const ::helloworld::GetEchoRequest* /*request*/, ::helloworld::GetEchoResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetEcho<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetEcho : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetEcho() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetEcho() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEcho(::grpc::ServerContext* /*context*/, const ::helloworld::GetEchoRequest* /*request*/, ::helloworld::GetEchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetEcho : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetEcho() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetEcho() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEcho(::grpc::ServerContext* /*context*/, const ::helloworld::GetEchoRequest* /*request*/, ::helloworld::GetEchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEcho(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetEcho : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetEcho() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetEcho(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetEcho() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEcho(::grpc::ServerContext* /*context*/, const ::helloworld::GetEchoRequest* /*request*/, ::helloworld::GetEchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetEcho(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetEcho : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetEcho() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::helloworld::GetEchoRequest, ::helloworld::GetEchoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::helloworld::GetEchoRequest, ::helloworld::GetEchoResponse>* streamer) {
                       return this->StreamedGetEcho(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetEcho() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetEcho(::grpc::ServerContext* /*context*/, const ::helloworld::GetEchoRequest* /*request*/, ::helloworld::GetEchoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetEcho(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::helloworld::GetEchoRequest,::helloworld::GetEchoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetEcho<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetEcho<Service > StreamedService;
};

}  // namespace helloworld


#endif  // GRPC_hello_2eproto__INCLUDED
