// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: simple.proto

#include "simple.pb.h"
#include "simple.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Simple {

static const char* Server_method_names[] = {
  "/Simple.Server/Echo",
};

std::unique_ptr< Server::Stub> Server::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Server::Stub> stub(new Server::Stub(channel, options));
  return stub;
}

Server::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Echo_(Server_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Server::Stub::Echo(::grpc::ClientContext* context, const ::Simple::EchoRequest& request, ::Simple::EchoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Simple::EchoRequest, ::Simple::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Echo_, context, request, response);
}

void Server::Stub::async::Echo(::grpc::ClientContext* context, const ::Simple::EchoRequest* request, ::Simple::EchoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Simple::EchoRequest, ::Simple::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Echo_, context, request, response, std::move(f));
}

void Server::Stub::async::Echo(::grpc::ClientContext* context, const ::Simple::EchoRequest* request, ::Simple::EchoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Echo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Simple::EchoResponse>* Server::Stub::PrepareAsyncEchoRaw(::grpc::ClientContext* context, const ::Simple::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Simple::EchoResponse, ::Simple::EchoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Echo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Simple::EchoResponse>* Server::Stub::AsyncEchoRaw(::grpc::ClientContext* context, const ::Simple::EchoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEchoRaw(context, request, cq);
  result->StartCall();
  return result;
}

Server::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Server_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Server::Service, ::Simple::EchoRequest, ::Simple::EchoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Server::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Simple::EchoRequest* req,
             ::Simple::EchoResponse* resp) {
               return service->Echo(ctx, req, resp);
             }, this)));
}

Server::Service::~Service() {
}

::grpc::Status Server::Service::Echo(::grpc::ServerContext* context, const ::Simple::EchoRequest* request, ::Simple::EchoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Simple

